name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Push Hugo to GitHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ${{ github.repository }}/hugo
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile-hugo
    - name: Push Caddy to GitHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ${{ github.repository }}/caddy
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile-caddy

    - name: Push Hugo to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: astrolox/hugo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile-hugo
    - name: Push Caddy to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: astrolox/caddy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile-caddy
